version: '3.4'

services:

  noteapi:
    build:
      context: .
      dockerfile: ./src/NoteApi/Dockerfile
    networks: 
      - noteapi_network
    depends_on:
      - postgresql
    restart: always
    environment: 
      - ConnectionStrings__PostgreSql=Host=postgresql;Database=note;Username=dbUser;Password=Test123456

  postgresql:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: Test123456
      POSTGRES_USER: dbUser
    networks: 
      - noteapi_network
    restart: always
    
  hiddenservice:
    image: bariskisir/hiddenservicereverseproxy
    environment: 
      HIDDEN_SERVICE_DIR: /var/lib/tor/hidden_service/
      HIDDEN_SERVICE_PORT: 80 noteapi:80
    depends_on:
      - noteapi
    networks: 
      - noteapi_network
    restart: always

networks:
  noteapi_network:
     driver: bridge